#!/bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/home/root/2obdgpslogger/obdgpslogger/bin/obdgpslogger
NAME=obdgpslogger
DESC="obdgpslogger"
OPTS="-a 2  -s /dev/tty01 -m"

case "$1" in
  start)
	echo -n "Starting $DESC: "
	#start-stop-daemon --start -x "$DAEMON" -- $OPTS
	stty -F /dev/obdii -crtscts -clocal ispeed 9600 ospeed 9600
	./home/root/2obdgpslogger/obdgpslogger/bin/obdgpslogger -s /dev/obdii -a 2 -d /home/root/obd.db &
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	#start-stop-daemon --stop -x "$DAEMON"
	killall obdgpslogger
	echo "$NAME."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "
	
	#start-stop-daemon --stop -x "$DAEMON"
	killall obdgpslogger
	sleep 1
	./home/root/2obdgpslogger/obdgpslogger/bin/obdgpslogger -a 2  -s /dev/tty01 -m &
	
	#start-stop-daemon --start -x "$DAEMON" -- $OPTS
	echo "$NAME."
	;;
  *)
	#N=/etc/init.d/$NAME
	#echo "Usage: $N {start|stop|restart|force-reload}" >&2
	#exit 1
	;;
esac

exit 0
